/** Mechanically transcribed registry descriptions from the authoritative protocol and indexing documents. */
export const authoritativeRegistryDescriptions = {
  "core:abstract": "type, callable",
  "core:aliases": "`alias E 1`; `target E,U 1..*`",
  "core:ambiguous_resolution": "symbol_resolution, type_information, module_dependencies, call_relationships, inheritance_and_implementation, framework_semantics",
  "core:ambiguous_target": "Resolution retained at least two competing targets and could not establish one unique confirmed target.",
  "core:analysis_budget_exhausted": "all 13 source-analysis capabilities",
  "core:analysis_configuration_digest": "`core:analysis_configuration`",
  "core:analysis_context_unavailable": "A frozen registry, configuration, plugin resolution, analyzer package, or required plugin dependency cannot be loaded and verified.",
  "core:analyze_impact": "target plus change descriptor",
  "core:analyzer_failed": "A registered analyzer terminates without producing a valid complete delta for its work item.",
  "core:analyzer_implementation_digest": "`core:analyzer_implementation`",
  "core:analyzer_timeout": "Analyzer execution exceeds the configured work-item deadline.",
  "core:api_version_unsupported": "`api_version` is syntactically valid but not one of the server's exact supported versions.",
  "core:artifact_analysis_metadata_digest": "`core:artifact_analysis_metadata`",
  "core:assertion": "A typed value validated by the concrete kind",
  "core:association": "`source E 1`; `target E,R,A,L,U 1..*`",
  "core:async": "callable, operation",
  "core:atomic_publication_failed": "The storage transaction cannot install the complete candidate tuple atomically.",
  "core:base_configuration_changed": "Publication sees a different current configuration from the candidate base. The candidate becomes stale.",
  "core:base_registry_changed": "Publication sees a different current registry from the candidate base. The candidate becomes stale.",
  "core:base_snapshot_changed": "Publication sees a different current snapshot from the candidate base. The candidate becomes stale.",
  "core:binary_not_semantic_text": "The artifact content is binary under the pinned decoder contract and is not semantic-text input.",
  "core:binding_relation": "binds_argument, handles, binds, covers",
  "core:binds": "`binding_site E:operation,construct 1`; `source E,L,U 1..*`; `target E,U 1..*`",
  "core:binds_argument": "`call_site E:operation+call_site 1`; `argument E:value,operation,resource,type,L 1`; `parameter E:value,type,U 1..*`",
  "core:branch_site": "operation",
  "core:budget_invalid": "An item, character, depth, work, or wait budget is zero, negative, above the advertised maximum, or illegal for the selected operation.",
  "core:build_context": "task statement, seeds, desired context facets",
  "core:call": "`caller E:callable,container 1`; `call_site E:operation+call_site 1`; `target E:callable,type,resource,U 1..*`; `argument E:value,operation,resource,type,L 0..* ordered`",
  "core:call_relationships": "resolved, typed, flow_sensitive, modeled, heuristic",
  "core:call_site": "operation",
  "core:callable": "A semantic unit that can be invoked, including functions, methods, constructors, lambdas, and operators. A type that can be constructed remains `core:type` with `core:constructible`.",
  "core:candidate_cleanup_failed": "Candidate-private materialization or an ended lease cannot be cleaned after the candidate reaches a terminal state.",
  "core:candidate_digest_mismatch": "Recomputed candidate content does not match its frozen `candidate_digest`.",
  "core:capability_unavailable": "No active compatible producer supplies a required analysis capability for the concrete source construct and artifact.",
  "core:captures": "`callable E:callable 1`; `captured_value E:value 1..*`; `capture_site E:operation,construct 0..1`",
  "core:compare": "role-bound participant subjects or scopes",
  "core:compare_workspaces": "compare two explicitly role-bound immutable workspace snapshots in one frozen execution.",
  "core:comparison_roles_base_target": "Query scope is `comparison` with exactly one `base` and one `target` participant.",
  "core:computed_property": "syntax_structure, symbol_declarations, symbol_resolution, type_information, call_relationships",
  "core:concurrency": "callable, operation",
  "core:conditional": "any relation except contains and defines",
  "core:configuration": "container, value, resource",
  "core:configuration_layer_digest": "`core:configuration_layer`",
  "core:constant_value": "A schema-tagged literal or closed structured constant",
  "core:construct": "A fallback semantic or synthetic construct with identity that cannot truthfully map to another entity base. Its concrete kind definition must document why no more specific base applies.",
  "core:constructible": "type",
  "core:construction": "call",
  "core:container": "A semantic unit whose primary purpose is grouping or organizing entities, such as a package, module, or namespace. A physical file remains a `SourceArtifact`, not an entity of this kind merely because it contains text.",
  "core:contains": "`container E:container,type,callable,resource,construct 1`; `contained E 1`",
  "core:control_flow": "`predecessor E:operation 1`; `successor E:operation 1`; `condition E:value,operation,L 0..1`",
  "core:core_registry_manifest_digest": "`core:core_registry_manifest`",
  "core:coverage_incomplete": "`require_complete` reaches its wait boundary while a non-semantic required capability remains non-complete.",
  "core:covers": "`test E:callable,container,resource 1`; `covered E 1..*`",
  "core:cursor_expired": "The cursor's execution lifetime has ended.",
  "core:cursor_invalid": "Cursor decoding, authentication, required claims, or execution lookup fails and expiry is not established.",
  "core:cursor_kind_mismatch": "A query cursor is supplied to index-status continuation or an index-status cursor is supplied to query continuation. No execution hydration is attempted.",
  "core:cursor_projection_mismatch": "Continuation attempts to change a result, evidence, diagnostic, registry, semantic-coverage, snippet, or status projection fixed by the cursor.",
  "core:cursor_stream_mismatch": "A cursor is supplied to an endpoint or continuation variant that cannot hydrate its selected stream.",
  "core:daemon_restart_required": "`urdira mcp` detects a live daemon for the selected data root whose engine build or private interface is incompatible, and safe coordinated replacement cannot proceed. No domain request is forwarded.",
  "core:data_flow": "`source E,R,L 1..*`; `sink E,R 1..*`; `flow_step E:operation+flow_step 1`",
  "core:declaration": "container, type, callable, value, resource, construct",
  "core:defines": "`declaration E+declaration 1`; `definition E+definition 1`",
  "core:definition": "container, type, callable, value, resource, construct",
  "core:definition_to_instances": "discover unfamiliar registered record kinds, facets, or languages and enumerate their exact visible record instances without a second agent call.",
  "core:delta_base_mismatch": "A delta names a base snapshot different from its candidate or work item.",
  "core:delta_id_conflict": "The same `fact_delta_id` is received with a digest different from the already accepted digest.",
  "core:delta_scope_mismatch": "Delta owner, plugin, version, capability, or replacement scope exceeds or contradicts its work item.",
  "core:dependency_relation": "import, depends_on",
  "core:dependency_validation_failed": "A proposed or derived artifact dependency is undeclared, inconsistent, unregistered, or cannot be closed deterministically.",
  "core:depends_on": "`dependent E 1`; `dependency E,A,U 1..*`",
  "core:deprecation": "Boolean `true`",
  "core:discover_definitions": "`DefinitionMatcher` plus optional registry selector",
  "core:documentation": "Source-owned comments, docstrings, prose, or documentation attached to the subject.",
  "core:duplicate_comparison_participant": "A comparison duplicates a role or exact workspace-snapshot coordinate, or repeats one workspace without distinct explicit snapshots.",
  "core:dynamic_import": "module_dependencies, symbol_resolution, call_relationships",
  "core:effect": "One registered namespaced effect string",
  "core:effects": "typed, flow_sensitive, modeled, heuristic",
  "core:embedding_generation_failed": "The exact pinned generator failed to produce valid deterministic vector bytes for one or more current segments owned by the artifact.",
  "core:embedding_input_digest": "`core:embedding_input`",
  "core:embedding_profile_content_unsupported": "The selected profile does not support the artifact's textual content class.",
  "core:embedding_profile_incompatible": "A known core-owned embedding profile cannot execute a semantic lane selected from pinned workspace configuration because a hard language, content, query-class, materialization, or generator condition is false.",
  "core:embedding_profile_language_unsupported": "The selected embedding profile does not declare support for a language present in the artifact.",
  "core:embedding_profile_not_found": "A profile pinned by the workspace configuration or retained semantic materialization is absent from at least one required registry snapshot.",
  "core:embedding_projection_updating": "Current semantic vectors are still being generated after negative invalidation removed superseded vectors.",
  "core:embedding_segment": "Profile-specific, token-bounded embedding input mapped to one semantic document and exact source spans.",
  "core:embedding_segmentation_failed": "The pinned profile segmenter could not produce valid source-mapped, token-bounded segments for a semantic document.",
  "core:embedding_template_digest": "`core:embedding_template`",
  "core:embedding_vector": "Canonically encoded deterministic vector for one exact embedding segment.",
  "core:embedding_vector_bytes_digest": "`core:embedding_vector_bytes`",
  "core:embedding_vectors_pending": "One or more current embedding segments have scheduled vector work that is not yet published.",
  "core:endpoint": "callable, resource",
  "core:entry_point": "container, callable, resource",
  "core:eval_like_execution": "syntax_structure, symbol_resolution, call_relationships, control_flow, data_flow, effects",
  "core:event_handler": "callable",
  "core:event_sink": "callable, resource",
  "core:event_source": "callable, resource",
  "core:exception": "callable, operation",
  "core:excluded_by_semantic_policy": "An explicit pinned configuration rule excludes the artifact from semantic indexing.",
  "core:execution_failed": "An unexpected core execution failure prevents a trustworthy manifest and no narrower registered code applies.",
  "core:execution_resource_limit": "Exact evaluation cannot finish within a declared hard work, memory, time, or intermediate-result limit.",
  "core:expand_relations": "subjects, direction, relation selector, depth",
  "core:explain_architecture_slice": "return an evidenced architectural slice and the source necessary to understand it.",
  "core:export": "`exporter E:container 1`; `export_site E:operation+export_site 1`; `exported E 1..* ordered`; `alias E:value,type,container,L 0..* ordered`",
  "core:export_site": "operation",
  "core:external": "any entity base; any relation base",
  "core:external_declaration": "symbol_resolution, type_information, module_dependencies, call_relationships, inheritance_and_implementation",
  "core:external_input_unavailable": "all source-analysis capabilities except syntax_structure over self-contained source",
  "core:find_paths": "source subjects, target subjects, relation selector",
  "core:find_records": "non-empty structural record selector",
  "core:find_references": "entity subject and reference-role selector",
  "core:find_related_tests": "subjects and test-relation policy",
  "core:find_relevant_tests": "return related tests and their fixtures, mocks, helpers, evidence, and source.",
  "core:flow_relation": "write, returns, binds_argument, control_flow, data_flow, throws",
  "core:flow_step": "operation",
  "core:framework_model_incomplete": "A recognized framework construct requires a semantic rule or metadata absent from the selected framework-model version.",
  "core:framework_model_missing": "call_relationships, effects, test_relationships, framework_semantics, semantic_preparation",
  "core:framework_semantics": "resolved, typed, modeled, heuristic",
  "core:freshness_wait_timeout": "`wait_for_current` reaches its explicit timeout before every participant has an equivalent freshness checkpoint.",
  "core:generated": "any entity base; any relation base",
  "core:generated_declaration": "syntax_structure, symbol_declarations, symbol_resolution, type_information, module_dependencies",
  "core:generated_source_unavailable": "syntax_structure, symbol_declarations, symbol_resolution, type_information, module_dependencies, call_relationships, inheritance_and_implementation, framework_semantics",
  "core:generator": "callable",
  "core:generator_configuration_digest": "`core:generator_configuration`",
  "core:get_outline": "artifact or container subject",
  "core:get_source": "exact subjects and snippet projection",
  "core:handles": "`handler E:callable,resource 1`; `handled E:value,type,resource,U 1..*`; `handler_site E:operation,construct 0..1`",
  "core:identity": "Deterministic subject name, qualified name, kind, and containing identity.",
  "core:identity_assignment_conflict": "Core identity resolution cannot produce one legal created or continued assignment.",
  "core:implementation": "Source-owned implementation body or semantically bounded implementation region.",
  "core:implements": "`implementer E:type,callable 1`; `implementation_site E:operation,construct 1`; `contract E:type,U 1..* ordered`",
  "core:implicit": "any entity base; any relation base",
  "core:import": "`importer E:container 1`; `import_site E:operation+import_site 1`; `imported E,A,U 1..* ordered`; `local_binding E:value,type,container 0..* ordered`",
  "core:import_site": "operation",
  "core:index_contract_unsupported": "The requested retained or imported index state requires a canonical encoding, hash algorithm, schema, digest domain, comparator, digest recipe, digest reference, or verifier contract that this engine cannot interpret losslessly.",
  "core:index_integrity_failed": "A mandatory requested snapshot or index component failed canonical digest or structural-integrity verification and cannot be returned as trusted intelligence.",
  "core:index_status": "explicit query workspace scope plus include options",
  "core:index_unavailable": "A required workspace has no published queryable snapshot.",
  "core:indirect": "references, call, read, write, type_of, data_flow, depends_on, binds",
  "core:inheritance_and_implementation": "resolved, typed, modeled",
  "core:inherits": "`subtype E:type 1`; `inheritance_site E:operation,construct 1`; `supertype E:type,U 1..* ordered`",
  "core:inspect_architecture": "scope and requested architectural views",
  "core:instance_definition_families": "Every selected definition, when any exist, is a `record_kind`, `facet`, or `language`. An empty exact definition set passes.",
  "core:invalid_definition_instance_selector": "`core:definition_to_instances` receives a selected definition family other than record kind, facet, or language. Empty exact discovery is valid and does not trigger this code.",
  "core:invalid_query_scope": "A recipe's closed scope guard rejects an otherwise schema-valid query scope.",
  "core:invalidation_plan_incomplete": "The planner cannot prove that every record or projection affected by the candidate seeds is covered, even after applying registered fallback scopes.",
  "core:io": "callable, operation",
  "core:keywords": "Deterministic normalized retrieval terms derived from local source or canonical records.",
  "core:literal": "value, operation, construct",
  "core:locate_implementation": "find concrete implementation-bearing definitions relevant to a task in one call.",
  "core:macro_expansion": "syntax_structure, symbol_declarations, symbol_resolution, type_information, call_relationships, control_flow, data_flow",
  "core:member": "container, type, callable, value, resource, construct",
  "core:member_container": "container, type, resource, construct",
  "core:metric": "Integer or number matching the registered metric value type",
  "core:missing_dependency": "A concrete source construct requires dependency source or semantics that configured providers and resolvers could not supply.",
  "core:model_identity_digest": "`core:model_identity`",
  "core:model_pack_runtime_configuration_digest": "`core:model_pack_runtime_configuration`",
  "core:module_dependencies": "syntactic, resolved, modeled",
  "core:mutation": "callable, operation",
  "core:network": "callable, operation",
  "core:nondeterminism": "callable, operation",
  "core:one_confirmed_subject": "The named stage has exactly one confirmed subject; possible alternatives may additionally be returned only in an ambiguity error detail.",
  "core:operation": "An executable or evaluated source construct that needs identity for relations, flow, or evidence, including calls, assignments, returns, branches, and flow steps.",
  "core:operation_cancelled": "Caller cancellation is observed before a ready manifest is published.",
  "core:operation_unknown": "No operation definition exists for the exact identifier under the selected API version.",
  "core:option_conflict": "Individually valid options violate a documented presence or interaction rule.",
  "core:overrides": "`overriding E:callable,value 1`; `overridden E:callable,value,U 1..*`",
  "core:parameter": "value",
  "core:parse_failed": "The configured parser did not produce a complete analysis-suitable syntax representation for the exact owner artifact version.",
  "core:participant_role_invalid": "A required role is missing, duplicated, unknown, or illegal for the selected operation.",
  "core:path": "Normalized artifact address and source-location context.",
  "core:persistence": "callable, operation",
  "core:plugin_cancelled": "The candidate or request cancellation identity is observed before a complete response is accepted.",
  "core:plugin_failed": "A plugin call other than the more specific analyzer/projection failures terminates without a complete valid response.",
  "core:plugin_inputs_incomplete": "A plugin request requires a source root or provider capability that the pinned analysis view cannot represent; ordinary undeclared cross-file reads do not qualify.",
  "core:plugin_package_digest": "`core:plugin_package`",
  "core:plugin_resource_exhausted": "A plugin request exceeds one exact `PluginResourceBudget` component before complete output is accepted.",
  "core:plugin_unsupported": "The negotiated plugin build explicitly does not implement the requested registered call/capability combination although activation selected it.",
  "core:prepare_new_feature": "find extension points, analogous implementations, architectural boundaries, tests, and bounded task context for new code.",
  "core:prepare_symbol_change": "resolve a symbol once and return its impact, references, tests, and exact relevant source.",
  "core:projection_digest_mismatch": "The complete generated projection set does not match the computed expected digest.",
  "core:projection_generator_failed": "A registered projection generator cannot finish its work item.",
  "core:projection_output_invalid": "Generated output violates projection schema, ownership, source, key, or visibility invariants.",
  "core:publication_conflict": "A uniqueness, compare-and-swap, generation, identity, or prior-publication conflict prevents this candidate from committing.",
  "core:query_configuration_digest": "`core:query_configuration`",
  "core:query_embedding_failed": "A mandatory semantic lane cannot create the exact query vector under its pinned executable binding.",
  "core:query_execution_evicted": "The execution expired early under an explicitly advertised emergency-eviction policy.",
  "core:query_plan_digest": "`core:query_plan`",
  "core:raw_artifact_content_digest": "`core:artifact_content`",
  "core:reachability": "`reachable`, `unreachable`, or `conditional`",
  "core:read": "`context E:callable,container 1`; `read_site E:operation+read_site 1`; `target E:value,resource,U 1..*`",
  "core:read_site": "operation",
  "core:recipe_unknown": "No recipe exists for the exact recipe ID.",
  "core:recipe_version_unsupported": "The recipe exists but the requested exact version is unsupported.",
  "core:record_schema_invalid": "A proposed record fails its registered envelope, kind, category-body, payload Schema IR, or canonical logical-type constraints.",
  "core:reexport": "export",
  "core:reference_relation": "aliases, type_of, references, call, read, write, import, export, inherits, implements, overrides, captures",
  "core:reference_validation_failed": "A proposed reference cannot satisfy its declared or governing target contract.",
  "core:references": "`reference_site E:operation,construct 1`; `target E,U 1..*`",
  "core:reflection": "symbol_resolution, call_relationships, data_flow, effects, framework_semantics",
  "core:registry_definition_unavailable": "A request references a definition absent from at least one required pinned registry.",
  "core:relationship_context": "Deterministic local rendering of names and kinds from canonical relations observed in the owner artifact.",
  "core:replacement_scope_incomplete": "A delta claiming complete replacement omits required output, coverage claims, or scope partitions.",
  "core:request_invalid": "Input is not an instance of the selected closed request schema after JSON decoding.",
  "core:required_capability_unsupported": "A mandatory operation capability is unsupported in at least one selected scope and the operation defines no accepted fallback.",
  "core:required_delta_missing": "Analysis finishes but no accepted delta covers one or more expected replacement scopes.",
  "core:resolve_and_find_references": "resolve a symbol and find all structurally indexed references in one frozen request.",
  "core:resolve_symbol": "name, optional location and `KindSelector`",
  "core:resource": "A logical externally addressable or configured element, such as a route, configuration key, database object, or message topic. It is not used for ordinary language symbols that fit another base.",
  "core:response_budget_digest": "`core:response_budget`",
  "core:retained_definition_unavailable": "Hydration cannot load a registry definition required to interpret a retained result page.",
  "core:return_site": "operation",
  "core:returns": "`callable E:callable 1`; `return_site E:operation+return_site 1`; `value E:value,operation,resource,L,U 0..1`",
  "core:runtime_component_behavior_digest": "`core:runtime_component_behavior`",
  "core:runtime_component_implementation_digest": "`core:runtime_component_implementation`",
  "core:runtime_dispatch": "symbol_resolution, call_relationships, control_flow, data_flow, effects",
  "core:scope": "container, type, callable, operation, resource, construct",
  "core:scope_mismatch": "Explicit continuation scope differs from the execution's ordered workspace IDs, comparison roles, or snapshot selectors.",
  "core:search_hybrid": "typed query text and hard filters",
  "core:search_semantic": "typed query text and hard filters",
  "core:search_text": "text or safe regex, path and kind filters",
  "core:selector_ambiguous": "A recipe guard requiring one confirmed subject receives more than one confirmed subject.",
  "core:selector_invalid": "A kind, facet, path, regex, namespace, registry, relation, or evidence selector violates its closed grammar or registry constraints.",
  "core:selector_not_found": "A recipe guard requiring one existing confirmed subject receives no confirmed subject.",
  "core:semantic_content_unsupported": "Included textual content cannot be represented by the selected decoder or embedding profile.",
  "core:semantic_coverage_incomplete": "A query requiring complete semantic coverage reached its explicit wait limit while relevant coverage remained non-complete.",
  "core:semantic_document": "Model-independent artifact or entity retrieval document with exact section provenance.",
  "core:semantic_document_failed": "Deterministic semantic-document construction failed for an included artifact occurrence.",
  "core:semantic_document_generation_failed": "The deterministic semantic-document generator could not produce a valid complete document for the exact owner artifact version or one of its entities.",
  "core:semantic_eligibility": "Deterministic source-owned semantic eligibility for one artifact occurrence.",
  "core:semantic_index_unavailable": "No queryable semantic materialization exists for a required workspace binding and profile.",
  "core:semantic_preparation": "syntactic, resolved, typed, modeled",
  "core:semantic_projection_failed": "Source-owned semantic document, segmentation, or embedding generation failed for part of the selected scope.",
  "core:semantic_query_generator_unavailable": "Indexed vectors exist, but the exact pinned query-vector generator is unavailable.",
  "core:semantic_retrieval": "modeled, heuristic",
  "core:semantic_role": "One registered namespaced semantic-role string",
  "core:semantic_to_callers": "combine semantic discovery, structural caller traversal, related tests, and source without an agent round trip.",
  "core:signature": "Source or canonical rendering of a callable, type, declaration, schema, or equivalent interface signature.",
  "core:snapshot_expired": "The snapshot identity is known but its queryable payload has been collected.",
  "core:snapshot_not_found": "An explicit snapshot ID is unknown or belongs to another workspace.",
  "core:snippet_budget_impossible": "The requested mandatory snippet projection cannot emit even one valid unit within the supplied character budget.",
  "core:source_content": "Generic source text not represented more precisely by another section kind.",
  "core:source_input_unavailable": "A required exact artifact version cannot be read or verified for candidate analysis.",
  "core:source_observation_conflict": "Two accepted observations cannot both be true under one provider ordering and coverage contract.",
  "core:source_provider_configuration_digest": "`core:source_provider_configuration`",
  "core:source_provider_deadline_exceeded": "A required source-provider call returns `deadline_exceeded` before a complete valid result is accepted.",
  "core:source_provider_failed": "A required source-provider call returns `failed` and no more specific source-provider code applies.",
  "core:source_provider_resource_exhausted": "A required source-provider call returns `resource_exhausted` for one exact resource limit.",
  "core:source_provider_state_changed": "An `enumerate`, `read`, or `reconcile` call returns `source_changed`, so its requested frozen source view cannot be accepted.",
  "core:source_provider_unavailable": "A required `describe`, `enumerate`, `read`, `watch`, or `reconcile` call returns `unavailable` while constructing or refreshing the candidate.",
  "core:source_state_digest": "`core:source_state`",
  "core:source_unavailable": "Hydration cannot read a source blob required by a selected result from its retained snapshot.",
  "core:stage_reference_invalid": "A stage input names a missing, later, or non-output stage coordinate.",
  "core:stage_type_mismatch": "An existing stage output type cannot satisfy the receiving operator input type.",
  "core:structural_relation": "contains, defines, aliases, type_of, inherits, implements, overrides",
  "core:symbol_declarations": "syntactic, resolved",
  "core:symbol_resolution": "resolved, typed, modeled, heuristic",
  "core:syntax_structure": "syntactic",
  "core:synthetic": "any entity base",
  "core:test": "container, callable, resource",
  "core:test_relationships": "resolved, typed, modeled, heuristic",
  "core:text_decoding_unsupported": "Text is inside semantic scope, but no active deterministic decoder can produce the required complete text representation.",
  "core:throws": "`callable E:callable,container 1`; `throw_site E:operation 1`; `value_or_type E:value,operation,type,L,U 1..*`",
  "core:tokenizer_identity_digest": "`core:tokenizer_identity`",
  "core:trace_behavior": "trace structurally evidenced behavior from explicit subjects without semantic retrieval.",
  "core:type": "A type-level abstraction or classifier, including classes, interfaces, structs, enums, traits, protocols, and type aliases.",
  "core:type_information": "typed, flow_sensitive, modeled",
  "core:type_of": "`subject E 1`; `type E:type,U 1..*`",
  "core:type_only": "import, export, references",
  "core:type_parameter": "type",
  "core:undeclared_input": "A proposal references an artifact version, base record, or staged record absent from the core-observed accepted access manifest or its proved transitive closure.",
  "core:understand_change_impact": "obtain affected code, contracts, tests, uncertainty, evidence, and source for one hypothetical change.",
  "core:unknown_field": "A closed request object contains at least one undeclared field.",
  "core:unregistered_identifier": "A proposal uses a kind, facet, role, code, capability, dependency role, or other registry identifier absent from the target registry.",
  "core:unresolved_symbol": "The configured resolution pipeline completed without a confirmed entity binding for the referenced symbol.",
  "core:unsupported_construct": "The construct was recognized, but one or more requested semantic capabilities are not implemented for it.",
  "core:value": "An identifiable value, binding, or storage location, including variables, constants, fields, properties, parameters, and enum members.",
  "core:work_manifest_inconsistent": "The frozen work manifest violates a structural or context invariant.",
  "core:workspace_not_found": "An explicit workspace ID has no registered workspace.",
  "core:workspace_not_registered": "An explicit API v2 workspace root has no exact registered workspace after canonicalization.",
  "core:write": "`context E:callable,container 1`; `write_site E:operation+write_site 1`; `target E:value,resource,U 1..*`; `value E:value,operation,resource,L,U 0..1`",
  "core:write_site": "operation"
} as const;
