import { spawn, type ChildProcessWithoutNullStreams } from "node:child_process";
import { createHash } from "node:crypto";
import { unlinkSync, writeFileSync } from "node:fs";
import { isAbsolute, resolve } from "node:path";
import { decodeRustWorkerMessage, encodeRustWorkerMessage, MAX_RUST_WORKER_MESSAGE_BYTES, RustWorkerFrameDecoder } from "./rust-protocol.js";
export interface IndexGenerationRequest {
  readonly operation_id: string; readonly workspace_id: string; readonly candidate_generation_id: string; readonly database_path: string;
  /** Private Rust checkpoint sidecar; normally generated by this transport. */
  readonly cancellation_path?: string;
  /** Private cutover switch for direct final-table promotion from Rust TEMP rows. */
  readonly direct_publication?: boolean;
  /** Explicit immutable CAS root captured before the generation is handed to Rust. */
  readonly cas_root: string;
  readonly source_snapshot_id: string; readonly source_state_digest: string; readonly base_generation: number;
  readonly registry_snapshot_id: string; readonly configuration_revision_id: string; readonly resolution_lock_id: string; readonly workspace_schema_digest?: string;
  readonly change_set: { readonly kind: "full" } | { readonly kind: "exact"; readonly changed_artifact_ids: readonly string[] };
  /** Generic Rust-owned candidate lifecycle metadata. */
  readonly candidate?: Readonly<Record<string, unknown>>;
  readonly frozen_base?: Readonly<Record<string, unknown>>;
  readonly work_manifest?: Readonly<Record<string, unknown>>;
  readonly engine: { readonly engine_id: string; readonly engine_version: string; readonly implementation_digest: string };
  readonly deadline_ms?: number;
  /** Opaque engine input consumed inside the Rust composition worker. */
  readonly engine_input?: Readonly<Record<string, unknown>>;
  readonly semantic_engine?: {
    readonly node_executable: string;
    readonly worker_entrypoint: string;
    readonly build_identity: string;
    readonly worker_descriptor: unknown;
    readonly structural_kernel_addon_path?: string;
  };
}
export type IndexingEvent =
  | { readonly kind: "handshake_ack"; readonly request_id: string; readonly protocol_identity: string; readonly protocol_version: number }
  | { readonly kind: "progress"; readonly request_id: string; readonly operation_id: string; readonly phase: string; readonly completed_groups: number; readonly completed_owners: number; readonly completed_rows: number; readonly affected_paths?: readonly string[]; readonly changed_paths?: readonly string[]; readonly dependency_graph?: Readonly<Record<string, { readonly direct_files: readonly string[]; readonly complete: boolean }>>; readonly analysis_token?: string }
  | { readonly kind: "semantic_result"; readonly request_id: string; readonly operation_id: string; readonly result: unknown }
  | { readonly kind: "completed"; readonly request_id: string; readonly operation_id: string; readonly generation: number; readonly group_count: number; readonly owner_count: number; readonly row_count: number; readonly ordered_digest: string; readonly lexical_closed?: number; readonly lexical_inserted?: number; readonly lexical_oversized?: number }
  | { readonly kind: "cancelled"; readonly request_id: string; readonly operation_id: string }
  | { readonly kind: "status"; readonly request_id: string; readonly operation_id: string; readonly phase: string; readonly active: boolean }
  | { readonly kind: "shutdown_ack"; readonly request_id: string }
  | { readonly kind: "source_index_committed"; readonly request_id: string; readonly operation_id: string; readonly commit_count: number }
  | { readonly kind: "source_index_rolled_back"; readonly request_id: string; readonly operation_id: string }
  | { readonly kind: "error"; readonly request_id: string; readonly code: string; readonly message: string };

export interface IndexingCoreProcessDescriptor {
  readonly command: string;
  readonly args?: readonly string[];
  readonly request_timeout_ms?: number;
  readonly max_message_bytes?: number;
  readonly scratch_directory?: string;
}

export interface IndexingCoreProcessTransport {
  readonly process_id: number;
  ready(): Promise<void>;
  indexGeneration(request: IndexGenerationRequest): Promise<IndexingEvent>;
  acceptGroup(operationId: string, group: unknown): Promise<IndexingEvent>;
  analyzeSemanticGroup(operationId: string, requests: readonly unknown[]): Promise<IndexingEvent>;
  invokeSemantic(operationId: string, request: unknown): Promise<IndexingEvent>;
  acceptCanonicalGroup(operationId: string, group: unknown): Promise<IndexingEvent>;
  finalizeGeneration(operationId: string, publication?: unknown): Promise<IndexingEvent>;
  commitSourceIndex(operationId: string, workspaceId: string, databasePath: string, commits: readonly unknown[], finalizeState?: boolean): Promise<IndexingEvent>;
  rollbackSourceIndex(operationId: string, workspaceId: string, databasePath: string): Promise<IndexingEvent>;
  cancel(operationId: string): Promise<IndexingEvent>;
  status(operationId: string): Promise<IndexingEvent>;
  shutdown(): Promise<void>;
  terminate(): Promise<void>;
}

type Request = { readonly request_id: string; readonly kind: string; readonly [key: string]: unknown };
type Pending = { readonly resolve: (event: IndexingEvent) => void; readonly reject: (error: Error) => void; readonly timer: NodeJS.Timeout };

function asError(value: unknown): Error { return value instanceof Error ? value : new Error(String(value)); }
// T3 (docs/evidence/2026-09-02-file-creation-diagnosis.md): this per-request
// timer is the only liveness signal this transport has for a still-pending
// `index_generation`/`accept_group`/... call -- the wire protocol is
// strictly request/response, so a `progress`-kind event IS the terminal
// response to whichever command sent it, never a mid-flight notification a
// pending call's timer could reset against. `MAX_REQUEST_TIMEOUT_MS` is a
// generous but still-finite safety-net ceiling (six times the previous
// hardcoded 600_000ms), configurable end-to-end via
// `URDIRA_INDEXING_CORE_TIMEOUT_MS` (see `indexingCoreRequestTimeoutMs` /
// `indexingCoreDeadlineMs` in `apps/urdira/src/index.ts`, which also raises
// the `deadline_ms` budget Rust's own internal checkpoints enforce, so
// raising this ceiling actually extends how long Rust keeps working, not
// just how long Node waits for a response Rust already abandoned).
const MAX_REQUEST_TIMEOUT_MS = 3_600_000;
function timeout(value: number | undefined): number {
  const result = value ?? 120_000;
  if (!Number.isSafeInteger(result) || result <= 0 || result > MAX_REQUEST_TIMEOUT_MS) throw new Error("indexing-core request_timeout_ms is invalid.");
  return result;
}
function validateEvent(value: unknown): IndexingEvent {
  if (typeof value !== "object" || value === null || Array.isArray(value) || typeof (value as { kind?: unknown }).kind !== "string") throw new Error("Indexing-core returned an invalid event.");
  return value as IndexingEvent;
}

/** Private framed transport for the composition worker. Owner rows are sent
 * only from the language engine to Rust; this port is never exposed by MCP. */
export function createIndexingCoreProcessTransport(descriptor: IndexingCoreProcessDescriptor): IndexingCoreProcessTransport {
  if (descriptor.command.length === 0) throw new Error("Indexing-core worker command is required.");
  const maxBytes = descriptor.max_message_bytes ?? MAX_RUST_WORKER_MESSAGE_BYTES;
  if (!Number.isSafeInteger(maxBytes) || maxBytes <= 0 || maxBytes > MAX_RUST_WORKER_MESSAGE_BYTES) throw new Error("Indexing-core max_message_bytes is invalid.");
  const child = spawn(descriptor.command, [...(descriptor.args ?? [])], {
    cwd: descriptor.scratch_directory,
    env: {
      PATH: process.env["PATH"] ?? "",
      ...(process.env["URDIRA_DEBUG_TIMING"] === "1" ? { URDIRA_DEBUG_TIMING: "1" } : {}),
      // F5 hybrid lane (E1b, docs/evidence/2026-09-01-f5-hybrid-design.md):
      // the Rust composition worker gates every hybrid-lane behavior behind
      // these three variables. Forward them only when explicitly set, same
      // hermetic-by-default shape as URDIRA_DEBUG_TIMING above.
      ...(process.env["URDIRA_JSTS_HYBRID"] !== undefined ? { URDIRA_JSTS_HYBRID: process.env["URDIRA_JSTS_HYBRID"] } : {}),
      ...(process.env["URDIRA_JSTS_HYBRID_STRICT_MERGE"] === "1" ? { URDIRA_JSTS_HYBRID_STRICT_MERGE: "1" } : {}),
      ...(process.env["URDIRA_JSTS_HYBRID_PARALLELISM"] !== undefined ? { URDIRA_JSTS_HYBRID_PARALLELISM: process.env["URDIRA_JSTS_HYBRID_PARALLELISM"] } : {}),
    },
    stdio: ["pipe", "pipe", "pipe"],
    windowsHide: true,
  }) as ChildProcessWithoutNullStreams;
  if (child.pid === undefined) { child.kill(); throw new Error("Indexing-core worker did not expose a process identity."); }
  const decoder = new RustWorkerFrameDecoder(maxBytes);
  const pending = new Map<string, Pending>();
  const cancellationMarkers = new Map<string, string>();
  const markerPath = (request: IndexGenerationRequest): string => request.cancellation_path === undefined
    ? resolve(`${request.database_path}.urdira-cancel-${createHash("sha256").update(request.operation_id).digest("hex")}`)
    : resolve(request.cancellation_path);
  const removeMarker = (operationId: string): void => {
    const path = cancellationMarkers.get(operationId);
    if (path === undefined) return;
    cancellationMarkers.delete(operationId);
    try { unlinkSync(path); } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
    }
  };
  const requestTimeout = timeout(descriptor.request_timeout_ms);
  let nextRequest = 1;
  let nextStream = 1;
  let healthy = true;
  let handshake: Promise<void> | undefined;
  let shutdownAcknowledged = false;
  const fail = (cause: unknown): Error => {
    const error = asError(cause); healthy = false;
    for (const path of cancellationMarkers.values()) {
      try { unlinkSync(path); } catch { /* best effort during process failure */ }
    }
    cancellationMarkers.clear();
    for (const item of pending.values()) { clearTimeout(item.timer); item.reject(error); }
    pending.clear();
    if (!child.killed) child.kill();
    return error;
  };
  child.stdout.on("data", (chunk: Buffer) => {
    try {
      for (const frame of decoder.push(chunk)) {
        const event = validateEvent(JSON.parse(frame.payload.toString("utf8")));
        const requestId = (event as { request_id?: unknown }).request_id;
        if (typeof requestId !== "string") throw new Error("Indexing-core event has no request identity.");
        const item = pending.get(requestId);
        if (item === undefined) throw new Error("Indexing-core returned an unknown request identity.");
        pending.delete(requestId); clearTimeout(item.timer);
        if (event.kind === "error") item.reject(new Error(`${event.code}: ${event.message}`)); else item.resolve(event);
        if (event.kind === "shutdown_ack") shutdownAcknowledged = true;
      }
    } catch (error) { fail(error); }
  });
  child.stderr.on("data", (chunk: Buffer) => {
    if (chunk.byteLength > 64 * 1024) fail(new Error("Indexing-core worker exceeded stderr allowance."));
    if (process.env["URDIRA_DEBUG_TIMING"] === "1") process.stderr.write(chunk);
  });
  child.on("error", fail);
  child.on("exit", (code, signal) => { if (healthy && !shutdownAcknowledged) fail(new Error(`Indexing-core worker exited (${code ?? signal ?? "unknown"}).`)); });
  const send = async (body: Omit<Request, "request_id">): Promise<IndexingEvent> => {
    if (!healthy) throw new Error("Indexing-core worker is unavailable.");
    const requestId = `indexing-core:${nextRequest++}`;
    const message = { ...body, request_id: requestId } as Request;
    const frames = encodeRustWorkerMessage(message, { stream_id: nextStream++, cancellation_id: requestId, byte_budget: maxBytes, in_flight_budget: maxBytes });
    return new Promise<IndexingEvent>((resolve, reject) => {
      const timer = setTimeout(() => { pending.delete(requestId); reject(fail(new Error("Indexing-core worker request timed out."))); }, requestTimeout);
      pending.set(requestId, { resolve, reject, timer });
      try { for (const frame of frames) child.stdin.write(frame); } catch (error) { reject(fail(error)); }
    });
  };
  const ready = async (): Promise<void> => {
    handshake ??= send({ kind: "handshake", protocol_identity: "urdira.indexing-core.v1" }).then((event) => {
      if (event.kind !== "handshake_ack" || event.protocol_identity !== "urdira.indexing-core.v1") throw new Error("Indexing-core handshake identity mismatch.");
    }).then(() => undefined);
    await handshake;
  };
  const call = async (body: Omit<Request, "request_id">): Promise<IndexingEvent> => { await ready(); return send(body); };
  return {
    process_id: child.pid,
    ready,
    indexGeneration: async (request) => {
      if (request.cas_root.length === 0 || request.cas_root.length > 4096 || !isAbsolute(request.cas_root) || /[\u0000\r\n\t]/u.test(request.cas_root)) throw new Error("Indexing-core generation CAS root is invalid.");
      const cancellation_path = markerPath(request);
      try { unlinkSync(cancellation_path); } catch (error) {
        if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
      }
      cancellationMarkers.set(request.operation_id, cancellation_path);
      try {
        // Keep the marker alive until finalize/cancel: publication planning may
        // continue in the application after the engine phase returns.
        return await call({ kind: "index_generation", request: { ...request, cancellation_path } });
      } catch (error) {
        removeMarker(request.operation_id);
        throw error;
      }
    },
    acceptGroup: (operation_id, group) => call({ kind: "accept_group", operation_id, group }),
    analyzeSemanticGroup: (operation_id, requests) => call({ kind: "analyze_semantic_group", operation_id, requests }),
    invokeSemantic: (operation_id, request) => call({ kind: "invoke_semantic", operation_id, request }),
    acceptCanonicalGroup: (operation_id, group) => call({ kind: "accept_canonical_group", operation_id, group }),
    finalizeGeneration: async (operation_id, publication) => {
      try {
        return await call({ kind: "finalize_generation", operation_id, ...(publication === undefined ? {} : { publication }) });
      } finally { removeMarker(operation_id); }
    },
    commitSourceIndex: (operation_id, workspace_id, database_path, commits, finalize_state = true) => call({ kind: "source_index_commit", operation_id, workspace_id, database_path, commits, finalize_state }),
    rollbackSourceIndex: (operation_id, workspace_id, database_path) => call({ kind: "source_index_rollback", operation_id, workspace_id, database_path }),
    cancel: async (operation_id) => {
      const path = cancellationMarkers.get(operation_id);
      if (path !== undefined) writeFileSync(path, "cancelled\n", { encoding: "utf8", flag: "w" });
      try { return await call({ kind: "cancel", operation_id }); } finally { removeMarker(operation_id); }
    },
    status: (operation_id) => call({ kind: "status", operation_id }),
    shutdown: async () => { await call({ kind: "shutdown" }); },
    terminate: async () => { healthy = false; for (const operationId of cancellationMarkers.keys()) removeMarker(operationId); if (!child.killed) child.kill(); decoder.finish(); },
  };
}
