import { spawn, type ChildProcessWithoutNullStreams } from "node:child_process";
import { createHash } from "node:crypto";
import { unlinkSync, writeFileSync } from "node:fs";
import { isAbsolute, resolve } from "node:path";
import { decodeRustWorkerMessage, encodeRustWorkerMessage, MAX_RUST_WORKER_MESSAGE_BYTES, RustWorkerFrameDecoder } from "./rust-protocol.js";
export interface IndexGenerationRequest {
  readonly operation_id: string; readonly workspace_id: string; readonly candidate_generation_id: string; readonly database_path: string;
  /** Private Rust checkpoint sidecar; normally generated by this transport. */
  readonly cancellation_path?: string;
  /** Private cutover switch for direct final-table promotion from Rust TEMP rows. */
  readonly direct_publication?: boolean;
  /** Explicit immutable CAS root captured before the generation is handed to Rust. */
  readonly cas_root: string;
  readonly source_snapshot_id: string; readonly source_state_digest: string; readonly base_generation: number;
  readonly registry_snapshot_id: string; readonly configuration_revision_id: string; readonly resolution_lock_id: string; readonly workspace_schema_digest?: string;
  readonly change_set: { readonly kind: "full" } | { readonly kind: "exact"; readonly changed_artifact_ids: readonly string[] };
  /** Generic Rust-owned candidate lifecycle metadata. */
  readonly candidate?: Readonly<Record<string, unknown>>;
  readonly frozen_base?: Readonly<Record<string, unknown>>;
  readonly work_manifest?: Readonly<Record<string, unknown>>;
  readonly engine: { readonly engine_id: string; readonly engine_version: string; readonly implementation_digest: string };
  readonly deadline_ms?: number;
  /** Opaque engine input consumed inside the Rust composition worker. */
  readonly engine_input?: Readonly<Record<string, unknown>>;
  readonly semantic_engine?: {
    readonly node_executable: string;
    readonly worker_entrypoint: string;
    readonly build_identity: string;
    readonly worker_descriptor: unknown;
    readonly structural_kernel_addon_path?: string;
  };
}
/** v4 cold/incremental scan protocol mirror (task P2-2b; Rust source of
 * truth: `crates/urdira-worker-protocol/src/lib.rs`'s `ScanScope`/
 * `ScanPriority`/`ScanTimings`/`ScanRoots`/`IndexingCommand::WorkspaceScan`/
 * `IndexingEvent::{Queryable,ScanCompleted}`). Kept in this file rather than
 * only in `packages/engine/src/rust-workspace-scan.ts` because this is the
 * literal wire shape sent to/decoded from the worker process, mirroring how
 * `IndexGenerationRequest`/`IndexingEvent` above are the wire shapes for the
 * v3 protocol. */
export type ChangedPathKind = "created" | "modified" | "deleted";
export interface ChangedPath {
  readonly path: string;
  readonly kind: ChangedPathKind;
}
export type ScanScope = { readonly kind: "full" } | { readonly kind: "changed"; readonly paths: readonly ChangedPath[] } | { readonly kind: "reconcile" };
export type ScanPriority = "interactive" | "background";
/** Frente E (plan `generic-waddling-hartmanis.md` §2.1): mirrors Rust's
 * `ReconcileMode`/`ReconcileSummary` -- see `rust-indexing-core-port.ts`'s
 * own copy of these two types for the field-by-field explanation. */
export type ReconcileMode = "noop" | "delta" | "cold";
export interface ReconcileSummary {
  readonly mode: ReconcileMode;
  readonly added: number;
  readonly changed: number;
  readonly deleted: number;
  readonly frontier_size: number;
  readonly threshold: number;
  readonly fell_back_to_cold: boolean;
  /** Frente E-fix: uris found content-equivalent but with a stale metadata
   * digest -- see `rust-indexing-core-port.ts`'s own copy for the full
   * explanation. */
  readonly metadata_refreshed: number;
}
export interface ScanTimings {
  readonly catalog_ms?: number;
  readonly parse_ms?: number;
  readonly resolve_ms?: number;
  readonly materialize_ms?: number;
  readonly write_ms?: number;
  readonly fsync_ms?: number;
  readonly snapshot_ms?: number;
  readonly lexical_ms?: number;
  readonly total_ms: number;
}
export interface ScanRoots {
  readonly records: string;
  readonly dependency: string;
  readonly graph: string;
  readonly metric: string;
}
export interface WorkspaceScanRequest {
  readonly workspace_id: string;
  readonly workspace_root: string;
  readonly database_path: string;
  readonly structural_root: string;
  readonly cas_root: string;
  readonly sidecar_root: string;
  readonly scope: ScanScope;
  readonly registry_snapshot_id: string;
  readonly configuration_revision_id: string;
  readonly resolution_lock_id: string;
  readonly deadline_ms?: number;
  readonly priority: ScanPriority;
}

export type IndexingEvent =
  | { readonly kind: "handshake_ack"; readonly request_id: string; readonly protocol_identity: string; readonly protocol_version: number }
  | { readonly kind: "progress"; readonly request_id: string; readonly operation_id: string; readonly phase: string; readonly completed_groups: number; readonly completed_owners: number; readonly completed_rows: number; readonly affected_paths?: readonly string[]; readonly changed_paths?: readonly string[]; readonly dependency_graph?: Readonly<Record<string, { readonly direct_files: readonly string[]; readonly complete: boolean }>>; readonly analysis_token?: string }
  | { readonly kind: "semantic_result"; readonly request_id: string; readonly operation_id: string; readonly result: unknown }
  | { readonly kind: "completed"; readonly request_id: string; readonly operation_id: string; readonly generation: number; readonly group_count: number; readonly owner_count: number; readonly row_count: number; readonly ordered_digest: string; readonly lexical_closed?: number; readonly lexical_inserted?: number; readonly lexical_oversized?: number }
  | { readonly kind: "cancelled"; readonly request_id: string; readonly operation_id: string }
  | { readonly kind: "status"; readonly request_id: string; readonly operation_id: string; readonly phase: string; readonly active: boolean }
  | { readonly kind: "shutdown_ack"; readonly request_id: string }
  | { readonly kind: "source_index_committed"; readonly request_id: string; readonly operation_id: string; readonly commit_count: number }
  | { readonly kind: "source_index_rolled_back"; readonly request_id: string; readonly operation_id: string }
  | { readonly kind: "error"; readonly request_id: string; readonly code: string; readonly message: string }
  /** v4: segments are on page cache, `MANIFEST.next` written; not durable yet. */
  | { readonly kind: "queryable"; readonly request_id: string; readonly operation_id: string; readonly generation: number; readonly manifest_path: string; readonly timings: ScanTimings; readonly reconcile?: ReconcileSummary }
  /** v4 terminal event for `workspace_scan`, kept distinct from `completed` (v3-shaped, closed). */
  | { readonly kind: "scan_completed"; readonly request_id: string; readonly operation_id: string; readonly generation: number; readonly snapshot_id: string; readonly roots: ScanRoots; readonly timings: ScanTimings; readonly reconcile?: ReconcileSummary }
  /** P1-D-c (decision 28): the background residual TypeScript-checker pass
   * finished for the workspace the `request_id`/`operation_id` scan
   * originally triggered, fired asynchronously well after that scan's own
   * `scan_completed` -- see `onUpgradeCompleted` below, not the ordinary
   * `pending`-map resolve-once dispatch every other event uses. */
  | { readonly kind: "upgrade_completed"; readonly request_id: string; readonly operation_id: string; readonly generation: number; readonly upgraded_sites: number; readonly external_sites: number; readonly unresolved_sites: number; readonly timings: ScanTimings; readonly truncated?: boolean; readonly windows_done?: number; readonly windows_total?: number; readonly checker_ms?: number };

export interface IndexingCoreProcessDescriptor {
  readonly command: string;
  readonly args?: readonly string[];
  readonly request_timeout_ms?: number;
  readonly max_message_bytes?: number;
  readonly scratch_directory?: string;
}

export interface IndexingCoreProcessTransport {
  readonly process_id: number;
  ready(): Promise<void>;
  indexGeneration(request: IndexGenerationRequest): Promise<IndexingEvent>;
  acceptGroup(operationId: string, group: unknown): Promise<IndexingEvent>;
  analyzeSemanticGroup(operationId: string, requests: readonly unknown[]): Promise<IndexingEvent>;
  invokeSemantic(operationId: string, request: unknown): Promise<IndexingEvent>;
  acceptCanonicalGroup(operationId: string, group: unknown): Promise<IndexingEvent>;
  finalizeGeneration(operationId: string, publication?: unknown): Promise<IndexingEvent>;
  commitSourceIndex(operationId: string, workspaceId: string, databasePath: string, commits: readonly unknown[], finalizeState?: boolean): Promise<IndexingEvent>;
  rollbackSourceIndex(operationId: string, workspaceId: string, databasePath: string): Promise<IndexingEvent>;
  cancel(operationId: string): Promise<IndexingEvent>;
  status(operationId: string): Promise<IndexingEvent>;
  /** v4 cold/incremental scan (task P2-2b). Resolves with the terminal
   * `scan_completed` event; `onQueryable`, if given, fires synchronously
   * when the earlier `queryable` event for the same request arrives (the
   * request is NOT resolved at that point -- unlike every other method
   * here, this one command produces two events sharing one `request_id`,
   * so the queryable milestone is delivered out-of-band instead of through
   * the resolve-once `pending` map). */
  workspaceScan(request: WorkspaceScanRequest, onQueryable?: (event: IndexingEvent & { readonly kind: "queryable" }) => void): Promise<IndexingEvent>;
  /** P1-D-c: subscribes to every `upgrade_completed` event this worker
   * process ever emits, for any workspace and any (possibly long-settled)
   * `workspace_scan` request -- unlike `workspaceScan`'s `onQueryable`, this
   * is NOT scoped to one in-flight call: the residual pass finishes
   * asynchronously, potentially minutes after the triggering scan's own
   * promise already resolved, so there is no live call to attach the
   * handler to at call time. The caller correlates `event.request_id` back
   * to a workspace itself (it is the same `request_id` that `workspaceScan`
   * call used). Returns an unsubscribe function; call it to stop listening
   * (e.g. on daemon shutdown for this transport). */
  onUpgradeCompleted(handler: (event: IndexingEvent & { readonly kind: "upgrade_completed" }) => void): () => void;
  shutdown(): Promise<void>;
  terminate(): Promise<void>;
}

type Request = { readonly request_id: string; readonly kind: string; readonly [key: string]: unknown };
type Pending = { readonly resolve: (event: IndexingEvent) => void; readonly reject: (error: Error) => void; readonly timer: NodeJS.Timeout };

function asError(value: unknown): Error { return value instanceof Error ? value : new Error(String(value)); }
// T3 (docs/evidence/2026-09-02-file-creation-diagnosis.md): this per-request
// timer is the only liveness signal this transport has for a still-pending
// `index_generation`/`accept_group`/... call -- the wire protocol is
// strictly request/response, so a `progress`-kind event IS the terminal
// response to whichever command sent it, never a mid-flight notification a
// pending call's timer could reset against. `MAX_REQUEST_TIMEOUT_MS` is a
// generous but still-finite safety-net ceiling (six times the previous
// hardcoded 600_000ms), configurable end-to-end via
// `URDIRA_INDEXING_CORE_TIMEOUT_MS` (see `indexingCoreRequestTimeoutMs` /
// `indexingCoreDeadlineMs` in `apps/urdira/src/index.ts`, which also raises
// the `deadline_ms` budget Rust's own internal checkpoints enforce, so
// raising this ceiling actually extends how long Rust keeps working, not
// just how long Node waits for a response Rust already abandoned).
const MAX_REQUEST_TIMEOUT_MS = 3_600_000;
function timeout(value: number | undefined): number {
  const result = value ?? 120_000;
  if (!Number.isSafeInteger(result) || result <= 0 || result > MAX_REQUEST_TIMEOUT_MS) throw new Error("indexing-core request_timeout_ms is invalid.");
  return result;
}
function validateEvent(value: unknown): IndexingEvent {
  if (typeof value !== "object" || value === null || Array.isArray(value) || typeof (value as { kind?: unknown }).kind !== "string") throw new Error("Indexing-core returned an invalid event.");
  return value as IndexingEvent;
}

/**
 * Fraction of the transport's byte budget one `source_index_commit` chunk is
 * allowed to fill. Left as headroom below `maxMessageBytes` for the rest of
 * the envelope (`operation_id`/`workspace_id`/`database_path`/`kind`/
 * `finalize_state`/`request_id`) and for `JSON.stringify`'s size being an
 * estimate of the eventual UTF-8-encoded frame payload, not an exact match.
 */
const SOURCE_INDEX_COMMIT_CHUNK_BUDGET_FRACTION = 0.9;

/**
 * Splits a `commit_source_index` payload's `commits` array into groups whose
 * estimated encoded size each stay under `maxMessageBytes`'s budget, so a
 * large deferred-commit batch (many artifact/version/observation rows
 * accumulated across one workspace scan, see
 * `packages/engine/src/workspace-indexing-session.ts`'s `deferredSourceCommits`)
 * can be sent to the Rust worker as several bounded messages instead of one
 * that can exceed `encodeRustWorkerMessage`'s hard cap
 * (`rust-protocol.ts`'s `MAX_RUST_WORKER_MESSAGE_BYTES`) and abort the whole
 * scan (see docs/evidence/2026-09-02-v4-p0-s4-promotion-gap.md, "Rust worker
 * message exceeds its byte or in-flight budget").
 *
 * `apply_source_index_commits` (`crates/urdira-indexing-worker/src/main.rs`)
 * already supports this split: every commit in a normal capture shares one
 * `expected_state_revision` (the single frontier the whole batch was read
 * against -- see that function's own comment), so each chunk's first commit
 * independently satisfies the revision check, and `finalize_state: false` on
 * every chunk but the last leaves `source_index_state` untouched until the
 * final chunk applies the real caller-requested `finalize_state`. Never
 * reorders or merges commit objects -- only groups whole ones, preserving
 * the original sequence.
 *
 * A single commit object that is already too large to fit alone (rare: it
 * would mean one accumulated batch, before any chunking, exceeds the byte
 * budget by itself) is still emitted alone in its own chunk rather than
 * dropped or mutated; the Rust worker's own byte-budget error at that point
 * is the accurate diagnostic; splitting one commit's inner rows is out of
 * scope here.
 */
export function chunkSourceIndexCommits(commits: readonly unknown[], maxMessageBytes: number): readonly (readonly unknown[])[] {
  if (commits.length <= 1) return [commits];
  const chunkBudgetBytes = Math.max(1, Math.floor(maxMessageBytes * SOURCE_INDEX_COMMIT_CHUNK_BUDGET_FRACTION));
  const sizes = commits.map((commit) => Buffer.byteLength(JSON.stringify(commit), "utf8"));
  if (sizes.reduce((total, size) => total + size, 0) <= chunkBudgetBytes) return [commits];
  const chunks: unknown[][] = [];
  let current: unknown[] = [];
  let currentBytes = 0;
  for (const [index, commit] of commits.entries()) {
    const size = sizes[index]!;
    if (current.length > 0 && currentBytes + size > chunkBudgetBytes) {
      chunks.push(current);
      current = [];
      currentBytes = 0;
    }
    current.push(commit);
    currentBytes += size;
  }
  if (current.length > 0) chunks.push(current);
  return chunks;
}

/** Private framed transport for the composition worker. Owner rows are sent
 * only from the language engine to Rust; this port is never exposed by MCP. */
export function createIndexingCoreProcessTransport(descriptor: IndexingCoreProcessDescriptor): IndexingCoreProcessTransport {
  if (descriptor.command.length === 0) throw new Error("Indexing-core worker command is required.");
  const maxBytes = descriptor.max_message_bytes ?? MAX_RUST_WORKER_MESSAGE_BYTES;
  if (!Number.isSafeInteger(maxBytes) || maxBytes <= 0 || maxBytes > MAX_RUST_WORKER_MESSAGE_BYTES) throw new Error("Indexing-core max_message_bytes is invalid.");
  const child = spawn(descriptor.command, [...(descriptor.args ?? [])], {
    cwd: descriptor.scratch_directory,
    env: {
      PATH: process.env["PATH"] ?? "",
      ...(process.env["URDIRA_DEBUG_TIMING"] === "1" ? { URDIRA_DEBUG_TIMING: "1" } : {}),
      // F5 hybrid lane (E1b, docs/evidence/2026-09-01-f5-hybrid-design.md):
      // the Rust composition worker gates every hybrid-lane behavior behind
      // these three variables. Forward them only when explicitly set, same
      // hermetic-by-default shape as URDIRA_DEBUG_TIMING above.
      ...(process.env["URDIRA_JSTS_HYBRID"] !== undefined ? { URDIRA_JSTS_HYBRID: process.env["URDIRA_JSTS_HYBRID"] } : {}),
      ...(process.env["URDIRA_JSTS_HYBRID_STRICT_MERGE"] === "1" ? { URDIRA_JSTS_HYBRID_STRICT_MERGE: "1" } : {}),
      ...(process.env["URDIRA_JSTS_HYBRID_PARALLELISM"] !== undefined ? { URDIRA_JSTS_HYBRID_PARALLELISM: process.env["URDIRA_JSTS_HYBRID_PARALLELISM"] } : {}),
      // P0-S2 prototype ("typeflow" resolver, urdira v4 plan; see
      // docs/evidence/2026-09-02-v4-p0-s2-typeflow-prototype.md). Same
      // forward-only-when-set shape as the hybrid-lane variables above --
      // the spawn only ever propagated PATH by default, so any new Rust-side
      // flag needs its own explicit line here or it never reaches the
      // worker process at all.
      ...(process.env["URDIRA_JSTS_TYPEFLOW"] !== undefined ? { URDIRA_JSTS_TYPEFLOW: process.env["URDIRA_JSTS_TYPEFLOW"] } : {}),
      ...(process.env["URDIRA_JSTS_TYPEFLOW_ORACLE"] !== undefined ? { URDIRA_JSTS_TYPEFLOW_ORACLE: process.env["URDIRA_JSTS_TYPEFLOW_ORACLE"] } : {}),
      ...(process.env["URDIRA_JSTS_TYPEFLOW_ORACLE_OUT"] !== undefined ? { URDIRA_JSTS_TYPEFLOW_ORACLE_OUT: process.env["URDIRA_JSTS_TYPEFLOW_ORACLE_OUT"] } : {}),
      // P1-D-c (decision 28): the background residual tsgo pass
      // (`crates/urdira-indexing-worker/src/v4/residual.rs`) is gated behind
      // this same forward-only-when-set convention -- without this line, a
      // daemon-set `URDIRA_V4_RESIDUAL` would never reach the worker
      // process at all, matching the typeflow flags above.
      ...(process.env["URDIRA_V4_RESIDUAL"] !== undefined ? { URDIRA_V4_RESIDUAL: process.env["URDIRA_V4_RESIDUAL"] } : {}),
      ...(process.env["URDIRA_TSGO_BINARY"] !== undefined ? { URDIRA_TSGO_BINARY: process.env["URDIRA_TSGO_BINARY"] } : {}),
      // Frente E (plan `generic-waddling-hartmanis.md` §2.6): the reconcile
      // delta/cold threshold-calibration harness
      // (`scripts/v4-reconcile-threshold.mjs`) forces `run_reconcile`'s `T`
      // to 1.0 (always take the `Delta` branch) or 0.0 (always take the
      // `Cold` fallback) by setting this on the SPAWNING process's own env
      // before calling `runRustWorkspaceScan` -- same forward-only-when-set
      // convention as every other Rust-side flag above; without this line
      // the override would never reach the worker subprocess at all
      // (production never sets it, so this is a no-op there).
      ...(process.env["URDIRA_V4_RECONCILE_THRESHOLD"] !== undefined ? { URDIRA_V4_RECONCILE_THRESHOLD: process.env["URDIRA_V4_RECONCILE_THRESHOLD"] } : {}),
    },
    stdio: ["pipe", "pipe", "pipe"],
    windowsHide: true,
  }) as ChildProcessWithoutNullStreams;
  if (child.pid === undefined) { child.kill(); throw new Error("Indexing-core worker did not expose a process identity."); }
  const decoder = new RustWorkerFrameDecoder(maxBytes);
  const pending = new Map<string, Pending>();
  // v4 `workspace_scan` side-channel (task P2-2b): the only command whose
  // request_id carries TWO events (`queryable` then the terminal
  // `scan_completed`). A handler registered here fires for the first
  // (non-terminal) event WITHOUT touching `pending`, so the normal
  // resolve-once dispatch below still owns the terminal event.
  const queryableHandlers = new Map<string, (event: IndexingEvent & { readonly kind: "queryable" }) => void>();
  // P1-D-c: persistent (never per-request, never removed on first fire)
  // subscriber set for `upgrade_completed` -- the one event kind this
  // transport can receive with NO corresponding `pending` entry at all
  // (the triggering `workspace_scan` call already resolved). Checked in the
  // dispatcher below, alongside (but independently of) `queryableHandlers`,
  // BEFORE the "unknown request identity" fatal-and-kill-the-process path
  // every other unrecognized frame still takes.
  const upgradeCompletedHandlers = new Set<(event: IndexingEvent & { readonly kind: "upgrade_completed" }) => void>();
  const cancellationMarkers = new Map<string, string>();
  const markerPath = (request: IndexGenerationRequest): string => request.cancellation_path === undefined
    ? resolve(`${request.database_path}.urdira-cancel-${createHash("sha256").update(request.operation_id).digest("hex")}`)
    : resolve(request.cancellation_path);
  const removeMarker = (operationId: string): void => {
    const path = cancellationMarkers.get(operationId);
    if (path === undefined) return;
    cancellationMarkers.delete(operationId);
    try { unlinkSync(path); } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
    }
  };
  const requestTimeout = timeout(descriptor.request_timeout_ms);
  let nextRequest = 1;
  let nextStream = 1;
  let healthy = true;
  let handshake: Promise<void> | undefined;
  let shutdownAcknowledged = false;
  const fail = (cause: unknown): Error => {
    const error = asError(cause); healthy = false;
    for (const path of cancellationMarkers.values()) {
      try { unlinkSync(path); } catch { /* best effort during process failure */ }
    }
    cancellationMarkers.clear();
    for (const item of pending.values()) { clearTimeout(item.timer); item.reject(error); }
    pending.clear();
    if (!child.killed) child.kill();
    return error;
  };
  child.stdout.on("data", (chunk: Buffer) => {
    try {
      for (const frame of decoder.push(chunk)) {
        const event = validateEvent(JSON.parse(frame.payload.toString("utf8")));
        const requestId = (event as { request_id?: unknown }).request_id;
        if (typeof requestId !== "string") throw new Error("Indexing-core event has no request identity.");
        // P3-5 (plan §6.1's daemon-latency item, rename residual): a `workspace_scan`
        // request_id used to be assumed to carry AT MOST one `queryable` event
        // before its terminal event -- true when the worker performs exactly
        // one internal generation, but NOT for a mixed burst that
        // `crates/urdira-indexing-worker/src/v4/delta.rs` (`run`) splits into
        // several internal generations for ONE `WorkspaceScan` command
        // (P3-2 item 5: a delete+create pair from a rename is exactly this
        // case) -- the worker emits one `queryable` PER internal generation,
        // all sharing this same `request_id`, before the single terminal
        // event for the whole command. The handler used to be deleted from
        // `queryableHandlers` on its FIRST invocation, so a second (or
        // later) `queryable` event fell through to the `pending` branch
        // below and was incorrectly resolved as if it were the terminal
        // event -- found live via a real end-to-end rename through the real
        // daemon+watcher (`docs/evidence/2026-09-03-v4-p3-5-daemon-latency.md`),
        // manifesting as `runRustWorkspaceScan` throwing "Rust workspace
        // scan returned an unexpected terminal event: queryable". Fixed by
        // keeping the handler registered (never deleting it here) and
        // firing it for EVERY `queryable` event that names this
        // `request_id`, however many arrive -- only the actual terminal
        // event (below) resolves `pending` and clears `queryableHandlers`.
        if (event.kind === "queryable") {
          const onQueryable = queryableHandlers.get(requestId);
          if (onQueryable !== undefined) {
            onQueryable(event);
            continue;
          }
        }
        // P1-D-c: dispatched to every subscriber, never through `pending`
        // (this event's `request_id` names a `workspace_scan` call that
        // settled long ago -- looking it up in `pending` would always miss
        // and, before this branch existed, fell through to the "unknown
        // request identity" throw below, which kills this whole child
        // process on the worker's first real `upgrade_completed` push).
        if (event.kind === "upgrade_completed") {
          for (const handler of upgradeCompletedHandlers) handler(event);
          continue;
        }
        const item = pending.get(requestId);
        if (item === undefined) throw new Error("Indexing-core returned an unknown request identity.");
        pending.delete(requestId); clearTimeout(item.timer);
        queryableHandlers.delete(requestId);
        if (event.kind === "error") item.reject(new Error(`${event.code}: ${event.message}`)); else item.resolve(event);
        if (event.kind === "shutdown_ack") shutdownAcknowledged = true;
      }
    } catch (error) { fail(error); }
  });
  child.stderr.on("data", (chunk: Buffer) => {
    if (chunk.byteLength > 64 * 1024) fail(new Error("Indexing-core worker exceeded stderr allowance."));
    if (process.env["URDIRA_DEBUG_TIMING"] === "1") process.stderr.write(chunk);
  });
  child.on("error", fail);
  child.on("exit", (code, signal) => { if (healthy && !shutdownAcknowledged) fail(new Error(`Indexing-core worker exited (${code ?? signal ?? "unknown"}).`)); });
  const sendWithId = async (requestId: string, body: Omit<Request, "request_id">): Promise<IndexingEvent> => {
    if (!healthy) throw new Error("Indexing-core worker is unavailable.");
    const message = { ...body, request_id: requestId } as Request;
    const frames = encodeRustWorkerMessage(message, { stream_id: nextStream++, cancellation_id: requestId, byte_budget: maxBytes, in_flight_budget: maxBytes });
    return new Promise<IndexingEvent>((resolve, reject) => {
      const timer = setTimeout(() => {
        pending.delete(requestId);
        queryableHandlers.delete(requestId);
        reject(fail(new Error("Indexing-core worker request timed out.")));
      }, requestTimeout);
      pending.set(requestId, { resolve, reject, timer });
      try { for (const frame of frames) child.stdin.write(frame); } catch (error) { reject(fail(error)); }
    });
  };
  const send = (body: Omit<Request, "request_id">): Promise<IndexingEvent> => sendWithId(`indexing-core:${nextRequest++}`, body);
  const ready = async (): Promise<void> => {
    handshake ??= send({ kind: "handshake", protocol_identity: "urdira.indexing-core.v1" }).then((event) => {
      if (event.kind !== "handshake_ack" || event.protocol_identity !== "urdira.indexing-core.v1") throw new Error("Indexing-core handshake identity mismatch.");
    }).then(() => undefined);
    await handshake;
  };
  const call = async (body: Omit<Request, "request_id">): Promise<IndexingEvent> => { await ready(); return send(body); };
  return {
    process_id: child.pid,
    ready,
    indexGeneration: async (request) => {
      if (request.cas_root.length === 0 || request.cas_root.length > 4096 || !isAbsolute(request.cas_root) || /[\u0000\r\n\t]/u.test(request.cas_root)) throw new Error("Indexing-core generation CAS root is invalid.");
      const cancellation_path = markerPath(request);
      try { unlinkSync(cancellation_path); } catch (error) {
        if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
      }
      cancellationMarkers.set(request.operation_id, cancellation_path);
      try {
        // Keep the marker alive until finalize/cancel: publication planning may
        // continue in the application after the engine phase returns.
        return await call({ kind: "index_generation", request: { ...request, cancellation_path } });
      } catch (error) {
        removeMarker(request.operation_id);
        throw error;
      }
    },
    acceptGroup: (operation_id, group) => call({ kind: "accept_group", operation_id, group }),
    analyzeSemanticGroup: (operation_id, requests) => call({ kind: "analyze_semantic_group", operation_id, requests }),
    invokeSemantic: (operation_id, request) => call({ kind: "invoke_semantic", operation_id, request }),
    acceptCanonicalGroup: (operation_id, group) => call({ kind: "accept_canonical_group", operation_id, group }),
    finalizeGeneration: async (operation_id, publication) => {
      try {
        return await call({ kind: "finalize_generation", operation_id, ...(publication === undefined ? {} : { publication }) });
      } finally { removeMarker(operation_id); }
    },
    commitSourceIndex: async (operation_id, workspace_id, database_path, commits, finalize_state = true) => {
      // See `chunkSourceIndexCommits`'s doc comment: a large batch is split
      // into several bounded messages rather than risking
      // `encodeRustWorkerMessage`'s hard byte-budget error. The common case
      // (one chunk) sends exactly the single request this always sent
      // before chunking existed.
      const chunks = chunkSourceIndexCommits(commits, maxBytes);
      let event: IndexingEvent | undefined;
      for (const [index, chunk] of chunks.entries()) {
        event = await call({ kind: "source_index_commit", operation_id, workspace_id, database_path, commits: chunk, finalize_state: index === chunks.length - 1 ? finalize_state : false });
      }
      return event!;
    },
    rollbackSourceIndex: (operation_id, workspace_id, database_path) => call({ kind: "source_index_rollback", operation_id, workspace_id, database_path }),
    cancel: async (operation_id) => {
      const path = cancellationMarkers.get(operation_id);
      if (path !== undefined) writeFileSync(path, "cancelled\n", { encoding: "utf8", flag: "w" });
      try { return await call({ kind: "cancel", operation_id }); } finally { removeMarker(operation_id); }
    },
    status: (operation_id) => call({ kind: "status", operation_id }),
    workspaceScan: async (request, onQueryable) => {
      await ready();
      const requestId = `indexing-core:${nextRequest++}`;
      if (onQueryable !== undefined) queryableHandlers.set(requestId, onQueryable);
      try {
        return await sendWithId(requestId, { kind: "workspace_scan", ...request });
      } finally {
        queryableHandlers.delete(requestId);
      }
    },
    onUpgradeCompleted: (handler) => {
      upgradeCompletedHandlers.add(handler);
      return () => { upgradeCompletedHandlers.delete(handler); };
    },
    shutdown: async () => { await call({ kind: "shutdown" }); },
    terminate: async () => { healthy = false; for (const operationId of cancellationMarkers.keys()) removeMarker(operationId); if (!child.killed) child.kill(); decoder.finish(); },
  };
}
