// Generated by scripts/generate-workspace-v3-sql.mjs; edit packages/storage/sql/workspace-v3.sql.
pub const WORKSPACE_V3_SCHEMA_DIGEST: &str =
    "sha256:93c7817fcd8eb04aab21dfda8da76ee14a2e8ecf739225318f4b7f8386987b6f";
