// Generated by scripts/generate-workspace-v3-sql.mjs; edit packages/storage/sql/workspace-v3.sql.
pub const WORKSPACE_V3_SCHEMA_DIGEST: &str =
    "sha256:e17aec3f523e810bfd7b8720d2bb253f3672fbd8ffa96b296312a68b333fd346";
