// Generated by scripts/generate-workspace-v3-sql.mjs; edit packages/storage/sql/workspace-v3.sql.
pub const WORKSPACE_V3_SCHEMA_DIGEST: &str =
    "sha256:fe4247ce6f0a53d0aebfa2283bd6ee865829ff88416d4082b91d246d7ae4e924";
