[package]
name = "urdira-jsts-indexing-engine"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
urdira-indexing-core = { version = "=0.1.0", path = "../urdira-indexing-core" }
urdira-jsts-native-projection = { version = "=0.1.0", path = "../urdira-jsts-native-projection" }
urdira-jsts-syntax-worker = { version = "=0.3.0", path = "../urdira-jsts-syntax-worker" }
urdira-worker-protocol = { version = "=0.1.0", path = "../urdira-worker-protocol" }
